<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Data driven testing suite" duration-ms="8424" started-at="2023-03-18T17:15:31Z" finished-at="2023-03-18T17:15:40Z">
    <groups>
    </groups>
    <test name="login standard user" duration-ms="3878" started-at="2023-03-18T17:15:31Z" finished-at="2023-03-18T17:15:35Z">
      <class name="sauceDemoTestNgTest.LoginDatadriven">
        <test-method status="PASS" signature="testStart()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@36d4b5c]" name="testStart" is-config="true" duration-ms="3850" started-at="2023-03-18T13:15:31Z" finished-at="2023-03-18T13:15:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method status="FAIL" signature="loginDataDriventest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@36d4b5c]" name="loginDataDriventest" duration-ms="12" started-at="2023-03-18T13:15:35Z" finished-at="2023-03-18T13:15:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/inventory.html]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sauceDemoElementsNG.NgLoginElementSauceDemo.findUserName(NgLoginElementSauceDemo.java:15)
	at sauceDemoTestNgTest.LoginDatadriven.loginDataDriventest(LoginDatadriven.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDataDriventest -->
        <test-method status="PASS" signature="testEnd()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@36d4b5c]" name="testEnd" is-config="true" duration-ms="0" started-at="2023-03-18T13:15:35Z" finished-at="2023-03-18T13:15:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnd -->
      </class> <!-- sauceDemoTestNgTest.LoginDatadriven -->
    </test> <!-- login standard user -->
    <test name="login locked out user" duration-ms="2155" started-at="2023-03-18T17:15:35Z" finished-at="2023-03-18T17:15:38Z">
      <class name="sauceDemoTestNgTest.LoginDatadriven">
        <test-method status="PASS" signature="testStart()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@7823a2f9]" name="testStart" is-config="true" duration-ms="2155" started-at="2023-03-18T13:15:35Z" finished-at="2023-03-18T13:15:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method status="FAIL" signature="loginDataDriventest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@7823a2f9]" name="loginDataDriventest" duration-ms="0" started-at="2023-03-18T13:15:38Z" finished-at="2023-03-18T13:15:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sauceDemoElementsNG.NgLoginElementSauceDemo.findUserName(NgLoginElementSauceDemo.java:15)
	at sauceDemoTestNgTest.LoginDatadriven.loginDataDriventest(LoginDatadriven.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDataDriventest -->
        <test-method status="PASS" signature="testEnd()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@7823a2f9]" name="testEnd" is-config="true" duration-ms="0" started-at="2023-03-18T13:15:38Z" finished-at="2023-03-18T13:15:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnd -->
      </class> <!-- sauceDemoTestNgTest.LoginDatadriven -->
    </test> <!-- login locked out user -->
    <test name="login problem_user " duration-ms="2250" started-at="2023-03-18T17:15:38Z" finished-at="2023-03-18T17:15:40Z">
      <class name="sauceDemoTestNgTest.LoginDatadriven">
        <test-method status="PASS" signature="testStart()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@6767c1fc]" name="testStart" is-config="true" duration-ms="2245" started-at="2023-03-18T13:15:38Z" finished-at="2023-03-18T13:15:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method status="FAIL" signature="loginDataDriventest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@6767c1fc]" name="loginDataDriventest" duration-ms="2" started-at="2023-03-18T13:15:40Z" finished-at="2023-03-18T13:15:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.saucedemo.com/inventory.html]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sauceDemoElementsNG.NgLoginElementSauceDemo.findUserName(NgLoginElementSauceDemo.java:15)
	at sauceDemoTestNgTest.LoginDatadriven.loginDataDriventest(LoginDatadriven.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDataDriventest -->
        <test-method status="PASS" signature="testEnd()[pri:0, instance:sauceDemoTestNgTest.LoginDatadriven@6767c1fc]" name="testEnd" is-config="true" duration-ms="0" started-at="2023-03-18T13:15:40Z" finished-at="2023-03-18T13:15:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEnd -->
      </class> <!-- sauceDemoTestNgTest.LoginDatadriven -->
    </test> <!-- login problem_user  -->
  </suite> <!-- Data driven testing suite -->
</testng-results>
